config/routes.rb
Rails.application.routes.draw do
  root 'me#index'
  get 'me/index'
  get 'me/travels'
  get 'me/about_me'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/me_controller.rb
class MeController < ApplicationController
  def index
  end

  def travels
  end

  def about_me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
      </button>
          </div>  
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="dropdown"></li>
              <li> <%= link_to image_tag("myAvatar.png", size: 30)%> </li>
              <li> <%= link_to "Home", me_index_path %></li>
              <li> <%= link_to "About Me", me_about_me_path %></li>
              <li> <%= link_to "Travels", me_travels_path %></li>
            </ul>
        </div>
      </nav>





    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/me/about_me.html.erb
<h1>About Me</h1>

<h3><em>Slightly</em> Nomadic</h3>
<p>From having moved more times than I care to count, to road-tripping to most every state. This is my life.</p>

app/views/me/index.html.erb
<div class="container-fluid">
	<h2>Me</h2>
	<div class="panel panel-primary">
		<div class="panel-heading">
			Mental meanderings
		</div>
		<div class="panel-body">
			Not all who wander are lost. Yet.
		</div>
	</div>
</div>

app/views/me/travels.html.erb
<h1>Places I've Been</h1>
<p>Oh, the places you will see. Oh, the places you will go.</p>